version: '3'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/usr/share/nginx/html/
      - ./ssl/:/ssl/
